### PR TITLE
Fix various things and add a test

### LINKED ISSUE #3: Construct Rto context lazily
It is more simple to setup RTO not with the construction of ModulePort, but later when the port is linked

### PR DESCRIPTION
**Pull request by junha1**
Fixes #3

### CODE REVIEW

File: module-rt/src/bootstrap.rs [hunk 1]
```diff
@@ -59,11 +59,9 @@ impl<T: UserModule + 'static> FoundryModule for ModuleContext<T> {
         self.user_context.replace(Arc::new(Mutex::new(module)));
```
Comment (majecty) [inline module-rt/src/bootstrap.rs:71]: In the " Construct RTO context lazily " commit.
Could you tell me why we need to create the RemoreTraitObject context lazily?

File: module-rt/src/example.rs [hunk 2]
```diff
@@ -0,0 +1,180 @@
+// Copyright 2020 Kodebox, Inc.
```
Comment (majecty) [inline module-rt/src/example.rs]: "Add a test" commit:

How about adding examples in the `examples` directory?
Cargo treats the examples directory specially.
https://doc.rust-lang.org/cargo/reference/cargo-targets.html?highlight=examples#examples

File: module-rt/src/example.rs [hunk 3]
```diff
@@ -0,0 +1,180 @@
...
+            my_greeting,
+            others_greeting,
+            hello_list: Vec::new(),
+        }
+    }
+
+    fn prepare_service_to_export(&mut self, ctor_name: &str, ctor_arg: &[u8]) -> Arc<dyn Dispatch> {
+        assert_eq!(ctor_name, "Constructor");
+        let value: i32 = serde_cbor::from_slice(ctor_arg).unwrap();
+        Arc::new(HelloBoxDispatcher::new(Box::new(SimpleHello {
```
Comment (majecty) [inline module-rt/src/example.rs]: Should we use `HelloBoxDispatcher`? Since it is a type generated by macro, using it in code is not a good example.

File: module-rt/src/bootstrap.rs [hunk 4]
```diff
@@ -43,35 +44,53 @@ impl ExportingServicePool {
...
+/// This service trait is compatible with FoundryModule, but slightly changed
+/// to share the Port
+#[remote_trait_object_macro::service]
+trait FoundryModuleInternal: Service {
+    fn initialize(&mut self, arg: &[u8], exports: &[(String, Vec<u8>)]);
+    fn create_port(&mut self, name: &str) -> SRwLock<dyn Port>;
+    fn debug(&mut self, arg: &[u8]) -> Vec<u8>;
+    fn shutdown(&mut self);
+}
+
```
Comment (majecty) [inline module-rt/src/bootstrap.rs:56]: How "FoundryModuleInternal" is related to the "Fix termination logic" commit?

File: module-rt/src/bootstrap.rs [hunk 5]
```diff
@@ -43,35 +44,53 @@ impl ExportingServicePool {
...
 struct ModuleContext<T: UserModule> {
     user_context: Option<Arc<Mutex<T>>>,
     exporting_service_pool: Arc<Mutex<ExportingServicePool>>,
+    ports: HashMap<String, Arc<RwLock<ModulePort<T>>>>,
```
Comment (majecty) [inline module-rt/src/bootstrap.rs:60]: How `ports` is related to "Fix termination logic" commit?

**Review by majecty — CHANGES_REQUESTED** [review]

File: module-rt/src/example.rs (hunk 3 above)
Comment (junha1) [reply module-rt/src/example.rs]: Oh yes you're right. Now it is possible via `ToDispatcher`. I'll update

File: module-rt/src/bootstrap.rs (hunk 1 above)
Comment (junha1) [reply module-rt/src/bootstrap.rs:71]: https://github.com/CodeChain-io/module-rt/issues/3
Since RTO context setup must be done concurrently with the other side, it should be done lazily not to cause a timeout in handshaking

File: module-rt/src/bootstrap.rs (hunk 4 above)
Comment (junha1) [reply module-rt/src/bootstrap.rs:56]: It allows `ModuleContext` to hold `ports`.

File: module-rt/src/bootstrap.rs (hunk 5 above)
Comment (junha1) [reply module-rt/src/bootstrap.rs:60]: To do this - https://github.com/CodeChain-io/module-rt/pull/4/files#diff-847a1b740457bf10416ff38c2bd69a0aR90

File: module-rt/src/example.rs (hunk 2 above)
Comment (junha1) [reply module-rt/src/example.rs]: content in `example.rs` will be actually imported in Foundry's test (`ModuleA`) Is it possible with that?

Comment (majecty) [reply module-rt/src/example.rs]: Exporting test or example code is not a normal thing. By doing it, changing test may need a version up.
Why do we need to export a test code?

Comment (junha1) [reply module-rt/src/example.rs]: Foundry will test `ModuleA` again with sandbox interface. If it bothers, we can just put two duplicated copies of `ModuleA` for each.

Comment (majecty) [reply module-rt/src/example.rs]: Let's copy the test. Increasing a version because we changed a test seems awkward.

Comment (junha1) [reply module-rt/src/example.rs]: ok

File: module-rt/src/bootstrap.rs (hunk 1 above)
Comment (majecty) [reply module-rt/src/bootstrap.rs:71]: Could you add a simple description in the commit message? You can link the issue.

Comment (junha1) [reply module-rt/src/bootstrap.rs:71]: ok

File: module-rt/src/bootstrap.rs (hunk 4 above)
Comment (majecty) [reply module-rt/src/bootstrap.rs:56]: ok

**Review by majecty — APPROVED** [review]
